### ISSUE TITLE
Problem Dataset 만들기

### ISSUE THREAD

**Issue by Ricepunchb** [JiHun-Lim/Prompter_Day_2023#7]
# Todo

- [x] 각 Generated Problem 별 solution, Answer 검수하기.
- [x] Original Problem, Generated Problem Dataset 따로 분리하기.
- [x] 검수 후 이상한 문제 있으면 지우고 새로 Generate 해서 채워넣기.

**Comment by Ricepunchb** [comment]
예상보다 solution 수율이 안좋음. Answer랑 맞는게 약 절반정도.. Gen problem의 문제일수도 있으니 Prompt를 달리해서 문제를 다르게 만들어 보는것부터 수정할 예정.
증명 문제들은 아직 solution 검토 중.

**Comment by Ricepunchb** [comment]
Problem Generate 부터 꼬이는것은 `Ori_dataset`에서 `Geneatable : False` 로, Problem은 괜찮게 generate 되나 Solution을 도저히 뽑아낼 수 없는 문제는 `gen_dataset`에서 `Valid : False` 로 표기함.

**Comment by Ricepunchb** [comment]
Ori_dataset에는 문제`index`를, gen_dataset에는 그 index 문제로부터 파생된 문제임을 식별가능하게 `GenNo.`를 수정함
